// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20251117175339_AddNewLessonNumber")]
    partial class AddNewLessonNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Infrastructure.DboModels.ClassroomDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleGroupId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("Infrastructure.DboModels.LessonDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchoolSubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("LessonNumberId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SchoolSubjectId");

                    b.HasIndex("StudyGroupId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Infrastructure.DboModels.LessonNumberDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("LessonNumbers");
                });

            modelBuilder.Entity("Infrastructure.DboModels.ScheduleDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleGroupId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Infrastructure.DboModels.ScheduleGroupDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScheduleGroups");
                });

            modelBuilder.Entity("Infrastructure.DboModels.SchoolSubjectDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleGroupId");

                    b.ToTable("SchoolSubjects");
                });

            modelBuilder.Entity("Infrastructure.DboModels.StudyGroupDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleGroupId");

                    b.ToTable("StudyGroups");
                });

            modelBuilder.Entity("Infrastructure.DboModels.TeacherDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleGroupId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolSubjectDboTeacherDbo", b =>
                {
                    b.Property<int>("SchoolSubjectsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SchoolSubjectsId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("SchoolSubjectDboTeacherDbo");
                });

            modelBuilder.Entity("StudyGroupDboTeacherDbo", b =>
                {
                    b.Property<int>("StudyGroupsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudyGroupsId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("StudyGroupDboTeacherDbo");
                });

            modelBuilder.Entity("Infrastructure.DboModels.ClassroomDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.ScheduleGroupDbo", "ScheduleGroup")
                        .WithMany("Classrooms")
                        .HasForeignKey("ScheduleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleGroup");
                });

            modelBuilder.Entity("Infrastructure.DboModels.LessonDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.ClassroomDbo", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.DboModels.LessonNumberDbo", "LessonNumber")
                        .WithMany()
                        .HasForeignKey("LessonNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.DboModels.ScheduleDbo", "Schedule")
                        .WithMany("Lessons")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.DboModels.SchoolSubjectDbo", "SchoolSubject")
                        .WithMany()
                        .HasForeignKey("SchoolSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.DboModels.StudyGroupDbo", "StudyGroup")
                        .WithMany()
                        .HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.DboModels.TeacherDbo", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("LessonNumber");

                    b.Navigation("Schedule");

                    b.Navigation("SchoolSubject");

                    b.Navigation("StudyGroup");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Infrastructure.DboModels.LessonNumberDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.ScheduleDbo", "Schedule")
                        .WithMany("LessonNumbers")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Infrastructure.DboModels.ScheduleDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.ScheduleGroupDbo", "ScheduleGroup")
                        .WithMany("Schedules")
                        .HasForeignKey("ScheduleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleGroup");
                });

            modelBuilder.Entity("Infrastructure.DboModels.SchoolSubjectDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.ScheduleGroupDbo", "ScheduleGroup")
                        .WithMany("SchoolSubjects")
                        .HasForeignKey("ScheduleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleGroup");
                });

            modelBuilder.Entity("Infrastructure.DboModels.StudyGroupDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.ScheduleGroupDbo", "ScheduleGroup")
                        .WithMany("StudyGroups")
                        .HasForeignKey("ScheduleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleGroup");
                });

            modelBuilder.Entity("Infrastructure.DboModels.TeacherDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.ScheduleGroupDbo", "ScheduleGroup")
                        .WithMany("Teachers")
                        .HasForeignKey("ScheduleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleGroup");
                });

            modelBuilder.Entity("SchoolSubjectDboTeacherDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.SchoolSubjectDbo", null)
                        .WithMany()
                        .HasForeignKey("SchoolSubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.DboModels.TeacherDbo", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyGroupDboTeacherDbo", b =>
                {
                    b.HasOne("Infrastructure.DboModels.StudyGroupDbo", null)
                        .WithMany()
                        .HasForeignKey("StudyGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.DboModels.TeacherDbo", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.DboModels.ScheduleDbo", b =>
                {
                    b.Navigation("LessonNumbers");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Infrastructure.DboModels.ScheduleGroupDbo", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Schedules");

                    b.Navigation("SchoolSubjects");

                    b.Navigation("StudyGroups");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Infrastructure.DboModels.TeacherDbo", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
